
spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  checkConfigLocation: true
#  configLocation: classpath:mybatis-config.xml
  configLocatio: classpath:mybatis-config.xml  #错误时，末尾缺少n
#  mapper-locations: classpath:mybatis/mapper/*.xml
  mapperLocations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.janloong.jingdg.doamin